### ISSUE TITLE
Bruke SpringBoot's database mekanismer

### ISSUE THREAD

**Issue by pdigre** [Thevyn/Eraseme#3]
Bruk av database
1. Bruk SpringBoot's mekanismer. Det er normalt å autowire en DataSource
2. Connection Pool. Det er for dyrt å åpne connection hver request, og i controlleren nå så er den heller ikke lukket. Det er ikke så viktig hvilken som blir valgt, HikariCP er den jeg har brukt oftest.
3. Skill ut JDBC ting i en repository service @Repository, eks https://mkyong.com/spring-boot/spring-boot-jdbc-mysql-hikaricp-example/
4. jdbcTemplate er det vanligste å bruke, men man kan også få connection,  Connection conn =  DataSourceUtils.getConnection(dataSource);

**Comment by Thevyn** [comment]
Fixed
